```{r}
library(dplyr)
library(sos)
library(tidyverse)
library(sqldf)
library(RColorBrewer)	
library(leaps)
library(mlbench)
library(caret)
library(randomForest)
library(MASS)
library(pROC)
library(rpart)
library(datapasta)
library(tree)
library(ade4)
library(caTools)
library(rpart)	
library(rpart.plot)
library(rattle)
library(party)					# Alternative decision tree algorithm
library(partykit)
library(caret)	
library(ISLR)
library(glmnet)
library(corrplot)
library(MLmetrics)
library(reshape2)
library(randomForest)
library(car)
library(scales)
library(treemap)
library(plotly)
library(e1071)
library(xgboost)
```

```{r}
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```


```{r}
data <- read.csv("hotel_bookings.csv", na.strings = " ")
#data
str(data)
data$is_canceled <- as.factor(data$is_canceled)
#data$children <- as.integer(data$children) - 1
```

```{r}
data_box <- data %>%
  dplyr::select(c(lead_time, stays_in_weekend_nights, stays_in_week_nights, adults, babies, previous_cancellations, previous_bookings_not_canceled, booking_changes, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, is_canceled))



boxplot(data_box)
db <- melt(data_box, id.var = "is_canceled")
ggplot(data = db, aes(x = variable, y = value)) + geom_boxplot(aes(fill = as.factor(is_canceled))) + coord_flip()
```